import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./NextAuthProvider";
import AuthProvider from "@/components/AuthProvider";
import { ReduxProvider } from "@/store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `Expense`,
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${inter.className} bg-neutral-content flex justify-center`}>
        <ReduxProvider>
         <NextAuthProvider>
           <AuthProvider>
             {children}
            </AuthProvider>
         </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
