import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./NextAuthProvider";
import AuthProvider from "@/components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `Expense`,
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${inter.className} bg-neutral-content min-h-[100vh] flex justify-center`}>
        <NextAuthProvider>
      <AuthProvider>
        {children}
      </AuthProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
